removed the variable. now dealing with the bucket directly

diff --git a/.github/workflows/main-wf.yml b/.github/workflows/main-wf.yml
--- a/.github/workflows/main-wf.yml
+++ b/.github/workflows/main-wf.yml
@@ -83,14 +83,16 @@ jobs:
             echo "No matching EC2 instances (Master or Worker-n) found."
           fi
 
-      # Check if the S3 bucket exists and delete it
+ 
       - name: Check and Delete S3 Bucket if Exists
         run: |
-          export BUCKET_NAME="k8s-infra-ssh-key"
-          aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null
+          aws s3api head-bucket --bucket k8s-infra-ssh-key 2>/dev/null
           if [ $? -eq 0 ]; then
-            echo "Deleting existing S3 bucket $BUCKET_NAME"
-            aws s3 rb s3://$BUCKET_NAME --force
+            echo "Deleting existing S3 bucket k8s-infra-ssh-key"
+            aws s3 rb s3://k8s-infra-ssh-key --force
+          elif [ $? -eq 255 ]; then
+            echo "AWS CLI encountered an error checking the bucket. Ensure that the AWS CLI is configured properly."
+            exit 255
           else
             echo "No existing S3 bucket found."
           fi
