remaining things fixed, now fixing the "delete duplicate bucket"

diff --git a/.github/workflows/main-wf.yml b/.github/workflows/main-wf.yml
--- a/.github/workflows/main-wf.yml
+++ b/.github/workflows/main-wf.yml
@@ -84,22 +84,22 @@ jobs:
           fi
 
  
-      # - name: Check and Delete S3 Bucket if Exists
-      #   run: |
-      #     export AWS_ACCESS_KEY_ID=${{ github.event.inputs.awsAccessKey }}
-      #     export AWS_SECRET_ACCESS_KEY=${{ github.event.inputs.awsSecretAccessKey }}
-      #     export AWS_REGION=${{ github.event.inputs.aws_region }}
+      - name: Check and Delete S3 Bucket if Exists
+        run: |
+          export AWS_ACCESS_KEY_ID=${{ github.event.inputs.awsAccessKey }}
+          export AWS_SECRET_ACCESS_KEY=${{ github.event.inputs.awsSecretAccessKey }}
+          export AWS_REGION=${{ github.event.inputs.aws_region }}
 
-      #     aws s3api head-bucket --bucket k8s-infra-ssh-key 2>/dev/null
-      #     if [ $? -eq 0 ]; then
-      #       echo "Deleting existing S3 bucket k8s-infra-ssh-key"
-      #       aws s3 rb s3://k8s-infra-ssh-key --force
-      #     elif [ $? -eq 255 ]; then
-      #       echo "AWS CLI encountered an error checking the bucket. Ensure that the AWS CLI is configured properly."
-      #       exit 255
-      #     else
-      #       echo "No existing S3 bucket found."
-      #     fi
+          aws s3api head-bucket --bucket k8s-infra-ssh-key 2>/dev/null
+          if [ $? -eq 0 ]; then
+            echo "Deleting existing S3 bucket k8s-infra-ssh-key"
+            aws s3 rb s3://k8s-infra-ssh-key --force
+          elif [ $? -eq 255 ]; then
+            echo "AWS CLI encountered an error checking the bucket. Ensure that the AWS CLI is configured properly."
+            exit 255
+          else
+            echo "No existing S3 bucket found."
+          fi
 
       # Check and Delete Security Groups if Exists
       - name: Check and Delete Security Groups if Exists
@@ -122,7 +122,7 @@ jobs:
           else
             echo "No existing worker security group found."
           fi
-          
+
       # Check and Delete EC2 Key Pair if Exists
       - name: Check and Delete EC2 Key Pair if Exists
         run: |
