delaying the bucket deletion for now

diff --git a/.github/workflows/main-wf.yml b/.github/workflows/main-wf.yml
--- a/.github/workflows/main-wf.yml
+++ b/.github/workflows/main-wf.yml
@@ -84,18 +84,18 @@ jobs:
           fi
 
  
-      - name: Check and Delete S3 Bucket if Exists
-        run: |
-          aws s3api head-bucket --bucket k8s-infra-ssh-key 2>/dev/null
-          if [ $? -eq 0 ]; then
-            echo "Deleting existing S3 bucket k8s-infra-ssh-key"
-            aws s3 rb s3://k8s-infra-ssh-key --force
-          elif [ $? -eq 255 ]; then
-            echo "AWS CLI encountered an error checking the bucket. Ensure that the AWS CLI is configured properly."
-            exit 255
-          else
-            echo "No existing S3 bucket found."
-          fi
+      # - name: Check and Delete S3 Bucket if Exists
+      #   run: |
+      #     aws s3api head-bucket --bucket k8s-infra-ssh-key 2>/dev/null
+      #     if [ $? -eq 0 ]; then
+      #       echo "Deleting existing S3 bucket k8s-infra-ssh-key"
+      #       aws s3 rb s3://k8s-infra-ssh-key --force
+      #     elif [ $? -eq 255 ]; then
+      #       echo "AWS CLI encountered an error checking the bucket. Ensure that the AWS CLI is configured properly."
+      #       exit 255
+      #     else
+      #       echo "No existing S3 bucket found."
+      #     fi
 
       # Check and Delete Security Groups if Exists
       - name: Check and Delete Security Groups if Exists
